# Generated by Django 6.0.5 on 2026-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_alter_tenantmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('resident', 'Resident'), ('parent', 'Parent')], default='staff', max_length=32),
        ),
    ]
