# Generated by Django 5.2.14 on 2026-05-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_bus', '0004_messaging_audit_fields'),
        ('tenancy', '0004_alter_tenantmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='paid_via',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('razorpay', 'Razorpay')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantmessagingconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='triplocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
