from django.urls import path

from .views import (
    DriverIncidentCreateView,
    DriverScheduleView,
    DriverTodayView,
    DriverTripAttendanceView,
    DriverTripCompleteView,
    DriverTripLocationView,
    DriverTripStartView,
    OperatorAttendanceExportView,
    OperatorAttendanceHistoryView,
    OperatorAttendanceSummaryView,
    OperatorBriefingView,
    OperatorDashboardView,
    OperatorLiveFleetView,
    OperatorTripSummaryView,
    OperatorTripsGenerateView,
    OperatorFeeRemindView,
    OperatorFeesGroupedView,
    OperatorHolidaysView,
    OperatorNotificationsLogView,
    OperatorReminderBroadcastView,
    OperatorTripsByDateView,
    OperatorTripsTodayView,
    ParentMeView,
    ParentRemindersView,
    RazorpayWebhookView,
    SchoolBusDashboardView,
    WhatsAppWebhookView,
)

urlpatterns = [
    path("dashboard/", SchoolBusDashboardView.as_view(), name="school-bus-dashboard"),
    path("operator/dashboard/", OperatorDashboardView.as_view(), name="sb-operator-dashboard"),
    path("operator/briefing/", OperatorBriefingView.as_view(), name="sb-operator-briefing"),
    path("operator/live-fleet/", OperatorLiveFleetView.as_view(), name="sb-operator-live-fleet"),
    path(
        "operator/trips/generate/",
        OperatorTripsGenerateView.as_view(),
        name="sb-operator-trips-generate",
    ),
    path("operator/holidays/", OperatorHolidaysView.as_view(), name="sb-operator-holidays"),
    path(
        "operator/trips/<int:trip_id>/summary/",
        OperatorTripSummaryView.as_view(),
        name="sb-operator-trip-summary",
    ),
    path("operator/fees/", OperatorFeesGroupedView.as_view(), name="sb-operator-fees"),
    path("operator/notifications/", OperatorNotificationsLogView.as_view(), name="sb-operator-notifications"),
    path(
        "operator/attendance-history/",
        OperatorAttendanceHistoryView.as_view(),
        name="sb-operator-attendance-history",
    ),
    path(
        "operator/attendance/summary/",
        OperatorAttendanceSummaryView.as_view(),
        name="sb-operator-attendance-summary",
    ),
    path(
        "operator/attendance/export/",
        OperatorAttendanceExportView.as_view(),
        name="sb-operator-attendance-export",
    ),
    path("operator/trips/today/", OperatorTripsTodayView.as_view(), name="sb-operator-trips-today"),
    path("operator/trips/", OperatorTripsByDateView.as_view(), name="sb-operator-trips-by-date"),
    path(
        "operator/fees/<int:fee_id>/remind/",
        OperatorFeeRemindView.as_view(),
        name="sb-operator-fee-remind",
    ),
    path("operator/reminders/", OperatorReminderBroadcastView.as_view(), name="sb-operator-reminders"),
    path("driver/today/", DriverTodayView.as_view(), name="sb-driver-today"),
    path("driver/schedule/", DriverScheduleView.as_view(), name="sb-driver-schedule"),
    path("driver/trips/<int:trip_id>/start/", DriverTripStartView.as_view(), name="sb-driver-trip-start"),
    path(
        "driver/trips/<int:trip_id>/attendance/",
        DriverTripAttendanceView.as_view(),
        name="sb-driver-trip-attendance",
    ),
    path(
        "driver/trips/<int:trip_id>/complete/",
        DriverTripCompleteView.as_view(),
        name="sb-driver-trip-complete",
    ),
    path(
        "driver/trips/<int:trip_id>/location/",
        DriverTripLocationView.as_view(),
        name="sb-driver-trip-location",
    ),
    path("webhooks/whatsapp/", WhatsAppWebhookView.as_view(), name="sb-webhook-whatsapp"),
    path("webhooks/razorpay/", RazorpayWebhookView.as_view(), name="sb-webhook-razorpay"),
    path("driver/incidents/", DriverIncidentCreateView.as_view(), name="sb-driver-incidents"),
    path("parent/me/", ParentMeView.as_view(), name="sb-parent-me"),
    path("parent/reminders/", ParentRemindersView.as_view(), name="sb-parent-reminders"),
]
