# Generated by Django 5.2.14 on 2026-05-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_management', '0003_resident_user_bookingrequest'),
        ('tenancy', '0003_alter_tenantmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
