"""Platform contract version — must match docs/contracts/README.md."""

REGISTRY_SCHEMA_VERSION = "1.0"
SUPPORTED_SCHEMA_MAJOR = 1

KERNEL_USER_RESOURCE_SLUG = "kernel-users"
KERNEL_USER_DISPLAY_FIELD = "username"

KERNEL_RELATION_DISPLAY_DEFAULTS = {
    "created_by": KERNEL_USER_DISPLAY_FIELD,
    "updated_by": KERNEL_USER_DISPLAY_FIELD,
    "resolved_by": KERNEL_USER_DISPLAY_FIELD,
}

USER_RELATION_FIELD_NAMES = frozenset(KERNEL_RELATION_DISPLAY_DEFAULTS.keys())
